### ISSUE TITLE
Error when running gridsome build

### ISSUE THREAD

**Issue by corneelonline** [shhdgit/vue-easy-slider#61]
Hi, I hope this is the right place to ask for help. I'm using vue-easy-slider in a Gridsome website and it works like a charm when running the site locally. With `gridsome develop` I can run the site on my local dev and the slider is fully functional.

I put the slider in it's own component btw. It looks like this:

```
<template>
  <section class="testimonials">
    <slider animation="normal" interval="8000">
      <slider-item v-for="edge in $static.testimonials.edges" :key="edge.node.id">
        <div class="testimonial" v-html="edge.node.content" />
        <div class="quote-by">{{edge.node.quote_by}}</div>
      </slider-item>
    </slider>
  </section>
</template>

<static-query>
query {
  testimonials: allTestimonial {
    edges {
      node {
        id
        title
        quote_by
        content
      }
    }
  }
}
</static-query>

<script>
import { Slider, SliderItem } from 'vue-easy-slider'

export default {
  name: 'TestimonialSlider',
  components: {
    Slider,
    SliderItem
  }
}
</script>

<style lang="scss">
all styles defined here...
</style>
```

When I want to deploy the website by running `gridsome build` the slider causes the following errors:
```
$ gridsome build
Gridsome v0.7.14

Initializing plugins...
Load sources - 0.11s
Create GraphQL schema - 0.12s
Create pages and templates - 0.06s
Generate temporary code - 0.03s
Bootstrap finish - 1.55s
Compile assets - 8.08s
Execute GraphQL (25 queries) - 0.06s
Write out page data (25 files) - 0.01s
Could not generate HTML for "/":
ReferenceError: document is not defined
    at addStyle (node_modules/vue-easy-slider/dist/vue-easy-slider.esm.js:715:0)
    at assets/js/vendors~page--src--pages--index-vue.1fbf38b4.js:703:12
    at a.__vue_inject_styles__ (node_modules/vue-easy-slider/dist/vue-easy-slider.esm.js:751:0)
    at a.hook (node_modules/vue-easy-slider/dist/vue-easy-slider.esm.js:661:0)
    at Ft (/PATH_TO_WEBSITE/node_modules/vue/dist/vue.runtime.common.prod.js:6:11191)
    at Ze (/PATH_TO_WEBSITE/node_modules/vue/dist/vue.runtime.common.prod.js:6:25133)
    at a.e._init (/PATH_TO_WEBSITE/node_modules/vue/dist/vue.runtime.common.prod.js:6:32564)
    at new a (/PATH_TO_WEBSITE/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
    at Vi (/PATH_TO_WEBSITE/node_modules/vue-server-renderer/build.prod.js:1:66307)
```
Do you have any idea what might cause this problem? Or do you suppose it's a Gridsome error?

**Comment by shhdgit** [comment]
OK, there's generate HTML error. I'll try Gridsome later.
